"""add cashier password_changed

Revision ID: 06c7088344eb
Revises: f8ee52e652bb
Create Date: 2026-03-29 03:39:38.117460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06c7088344eb'
down_revision: Union[str, None] = 'f8ee52e652bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashiers', sa.Column('password_changed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashiers', 'password_changed')
    # ### end Alembic commands ###
