"""initial schema

Revision ID: 4f21181caebb
Revises: 
Create Date: 2026-03-28 19:54:08.093784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f21181caebb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('common_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('from_name', sa.String(length=200), nullable=False),
    sa.Column('from_address', sa.Text(), nullable=False),
    sa.Column('from_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('from_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('to_name', sa.String(length=200), nullable=False),
    sa.Column('to_address', sa.Text(), nullable=False),
    sa.Column('to_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('to_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('distance_miles', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('prices', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('geofence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('polygon', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('default_commission_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('recipient', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('related_type', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicle_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.Column('base_fare', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('per_mile_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_passengers', sa.Integer(), nullable=False),
    sa.Column('max_luggage', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_type')
    )
    op.create_table('cashiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('ref_code', sa.String(length=20), nullable=False),
    sa.Column('commission_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_referrals', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashiers_ref_code'), 'cashiers', ['ref_code'], unique=True)
    op.create_table('drivers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('vehicle_make', sa.String(length=100), nullable=True),
    sa.Column('vehicle_plate', sa.String(length=20), nullable=True),
    sa.Column('vehicle_color', sa.String(length=30), nullable=True),
    sa.Column('vehicle_photo_url', sa.Text(), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('license_photo_url', sa.Text(), nullable=True),
    sa.Column('has_insurance', sa.Boolean(), nullable=False),
    sa.Column('pay_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('payout_method', sa.String(length=20), nullable=False),
    sa.Column('payout_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('stripe_connect_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('rating_avg', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_rides', sa.Integer(), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('last_online_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_drivers_status'), 'drivers', ['status'], unique=False)
    op.create_index(op.f('ix_drivers_vehicle_type'), 'drivers', ['vehicle_type'], unique=False)
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('upsales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vehicle_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('driver_gets_upsale', sa.Boolean(), nullable=False),
    sa.Column('cashier_gets_upsale', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_number', sa.String(length=20), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_phone', sa.String(length=20), nullable=False),
    sa.Column('client_room', sa.String(length=20), nullable=True),
    sa.Column('pickup_name', sa.String(length=200), nullable=False),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('pickup_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('dropoff_name', sa.String(length=200), nullable=False),
    sa.Column('dropoff_address', sa.Text(), nullable=False),
    sa.Column('dropoff_lat', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('dropoff_lng', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('distance_miles', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('pickup_time', sa.Time(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('luggage', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=20), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('extras_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('upsale_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('common_route_id', sa.UUID(), nullable=True),
    sa.Column('upsale_id', sa.UUID(), nullable=True),
    sa.Column('extras_chosen', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cashier_id', sa.UUID(), nullable=True),
    sa.Column('hotel_id', sa.UUID(), nullable=True),
    sa.Column('driver_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('start_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('end_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cashier_id'], ['cashiers.id'], ),
    sa.ForeignKeyConstraint(['common_route_id'], ['common_routes.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ),
    sa.ForeignKeyConstraint(['upsale_id'], ['upsales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_booking_number'), 'bookings', ['booking_number'], unique=True)
    op.create_index(op.f('ix_bookings_cashier_id'), 'bookings', ['cashier_id'], unique=False)
    op.create_index(op.f('ix_bookings_driver_id'), 'bookings', ['driver_id'], unique=False)
    op.create_index(op.f('ix_bookings_hotel_id'), 'bookings', ['hotel_id'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_session_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('refund_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_payment_id'), 'payments', ['stripe_payment_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='rating_range'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_index(op.f('ix_ratings_driver_id'), 'ratings', ['driver_id'], unique=False)
    op.create_table('payment_splits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('payout_trigger', sa.String(length=20), nullable=False),
    sa.Column('payout_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('stripe_transfer_id', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_splits_payment_id'), 'payment_splits', ['payment_id'], unique=False)
    op.create_index(op.f('ix_payment_splits_payout_status'), 'payment_splits', ['payout_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_splits_payout_status'), table_name='payment_splits')
    op.drop_index(op.f('ix_payment_splits_payment_id'), table_name='payment_splits')
    op.drop_table('payment_splits')
    op.drop_index(op.f('ix_ratings_driver_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_payments_stripe_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_hotel_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_driver_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_cashier_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_booking_number'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('upsales')
    op.drop_table('settings')
    op.drop_index(op.f('ix_drivers_vehicle_type'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_status'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_cashiers_ref_code'), table_name='cashiers')
    op.drop_table('cashiers')
    op.drop_table('vehicle_rates')
    op.drop_table('notification_log')
    op.drop_table('hotels')
    op.drop_table('geofence')
    op.drop_table('extras')
    op.drop_table('common_routes')
    op.drop_table('admins')
    # ### end Alembic commands ###
