"""add driver password_changed

Revision ID: d4fb04e2e7b4
Revises: 06c7088344eb
Create Date: 2026-03-29 05:29:12.608733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4fb04e2e7b4'
down_revision: Union[str, None] = '06c7088344eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('password_changed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'password_changed')
    # ### end Alembic commands ###
