"""add cashier payout fields

Revision ID: f8ee52e652bb
Revises: 4f21181caebb
Create Date: 2026-03-29 00:41:43.309398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8ee52e652bb'
down_revision: Union[str, None] = '4f21181caebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cashiers', sa.Column('payout_method', sa.String(length=20), server_default='bank', nullable=False))
    op.add_column('cashiers', sa.Column('payout_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cashiers', sa.Column('stripe_connect_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cashiers', 'stripe_connect_id')
    op.drop_column('cashiers', 'payout_details')
    op.drop_column('cashiers', 'payout_method')
    # ### end Alembic commands ###
